#ifndef _SCREENSIZE_H
#define _SCREENSIZE_H

#include <hp165x.h>

#ifndef DEFAULT_SCREEN_HEIGHT
#define DEFAULT_SCREEN_HEIGHT ROM_SCREEN_HEIGHT
#endif

#ifndef SCREEN_WIDTH
#define SCREEN_WIDTH ROM_SCREEN_WIDTH
#endif
#define SCREEN_WIDTH_BYTES  (SCREEN_WIDTH/2)
#define SCREEN_WIDTH_WORDS  (SCREEN_WIDTH/4)
#define SCREEN_WIDTH_DWORDS (SCREEN_WIDTH/8)

#endif